site de filmes/main.py
from flask import Flask 
from routes.home import home_route
from routes.filmes import filmes_route
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(filmes_route,url_prefix='/filmes')

app.run(debug=True)

site de filmes/routes/filmes.py
from flask import Blueprint,render_template,request
from database.database import  db,Filme

db.connect()
db.create_tables ([Filme])

filmes_route = Blueprint('filmes', __name__)


##------------lista de filmes X-----------##
@filmes_route.route('/')
def lista_filmes():
    return render_template('lista_filmes.html',filmes=Filme.select())

##---------------------------------------##






##------------inserir filme X----------------##
@filmes_route.route('/', methods=['POST'])
def inserir_filme():
    nome = request.form.get("nome")
    nota = request.form.get("nota")
    filme_novo=Filme.create(nome=nome,nota=float(nota))
    print(filme_novo.nome,type(filme_novo.nota))
    
    
    return render_template("item_filme.html",filme=filme_novo)

   
    
##---------------------------------------##






##------------novo filme X----------------##
@filmes_route.route('/new')
def form_filme():
    filme=False
    return render_template('form_filme.html',filme=filme)

##---------------------------------------##






##------------detalhes filme----------------##
@filmes_route.route('/<int:filme_id>')
def detalhe_filmes(filme_id):
     filme = Filme.get_by_id(filme_id)
     return render_template('detalhe_filmes.html',filme=filme)

##---------------------------------------##





##------------editar filme----------------##
@filmes_route.route('/<int:filme_id>/edit')
def form_edit_filme(filme_id):
    filme = Filme.get_by_id(filme_id)
    return render_template("form_filme.html",filme=filme)
##----------------------------------------------------------##




##------------Atualizar filme X----------------##
@filmes_route.route('/<int:filme_id>/uptade',methods =['PUT'])
def altualizar_filme(filme_id):
    filme = Filme.get_by_id(filme_id)
    data=request.json
    filme.nome=data["nome"]
    filme.nota=float(data["nota"])
    filme.save()
            
    return render_template('item_filme.html',filme=filme)
##------------------------------------------------------------------##






##----------------------deletar filme X------------------------------##
@filmes_route.route('/<int:filme_id>/delete', methods=['DELETE'])
def deletar_filme(filme_id):
    filme = Filme.get_by_id(filme_id)
    filme.delete_instance()
    return{'deleted':'ok'}   

site de filmes/routes/home.py
from flask import Blueprint,render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home ():
    return render_template('index.html')

site de filmes/templates/detalhe_filmes.html
<ul>
    <li> ID: {{filme.id}}</li>
    <li> NOME: {{filme.nome}}</li>
    <li> NOTA: {{filme.nota}}</li>
</ul>

site de filmes/templates/form_filme.html
<form class="c-form"
      {% if filme %}
        action="{{ url_for('filmes.altualizar_filme', filme_id=filme.id) }}" 
      {% else %}
        action="/" 
      {% endif %}
      method="{% if filme %}PUT{% else %}POST{% endif %}" 
      {% if filme %}
        c-swap="#filmes-{{filme.id}}"
      {% else %}
        c-append="#lista-filmes"
      {% endif %}
      c-reload-container="true">
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control fundo_form " name="nome"{% if filme %}value="{{filme.nome}}"{% endif %}>
    </div>

    <div class="mb-3">
      <label class="form-label">Nota</label>
      <input type="text" class="form-control fundo_form" name="nota"{% if filme %}value="{{filme.nota}}"{% endif %}>
    </div>
   
    <button type="submit" class="btn btn-primary"> 
      {% if filme %}Salvar{% else %}Criar{% endif %}
    </button>

</form>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

site de filmes/templates/index.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Maçã Quente</title>
    <link rel="shortcut icon" href="/static/oo.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for ('static', filename='style.css') }}">
  </head>
  <body>
      <a class="btn btn-primary" href="/filmes/new">Criar novo filme</a></button>
    <div class="container">
    <h1 class="text-center"> Maçã Quente </h1>
     
    

    <hr>
    <h2>Lista de filmes</h2>

    <div  id="form_filme" 
    c-container="{{url_for('filmes.lista_filmes')}}"></div>
    </div>

    <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content bg-dark">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">EXPECIFICAÇÃO</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id ="exibir-filme">
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{url_for ('static', filename='cru.js') }}"></script>
  </body>
</html>

site de filmes/templates/item_filme.html
<div class="col-sm-3" id="filmes-{{filme.id}}">
  <a href="/{{filme.id}}"> 
    <div class="card m-2" style="width: 100%">
      <img src="..." class="card-img-top" alt="..." />
      <div class="card-body">
        <h5 class="card-title">{{ filme.nome }}</h5>
        <p class="card-text">
          Some quick example text to build on the card title and make up the
          bulk of the card's content.
        </p>
      </div>
      <ul class="list-group list-group-flush">
        <li
          class="list-group-item {% if filme.nota >= 8.5 %} text-success{% elif filme.nota >= 6 and filme.nota < 8.5 %} text-warning{% else %}text-danger{% endif %}"
        >
          {{ filme.nota }}
        </li>
      </ul>
      <div class="card-body">
        <a
          href="#"
          class="card-link"
          c-get="{{url_for('filmes.form_edit_filme',filme_id=filme.id)}}"
          c-target="#form_filme"
          >Editar</a
        >
        <a
          c-delete="{{url_for('filmes.deletar_filme',filme_id=filme.id)}}"
          c-remove-closest="#filmes-{{filme.id}}"
          href="#"
          class="card-link"
          class="btn btn-outline-danger"
          >Delete</a
        >
      </div>
    </div>
  </a>
</div>

<!--
<tr id="filmes-{{filme.id}}">
  <th scope="row">{{ filme.id }}</th>
  <td>{{ filme.nome }}</td>
  <td <td>
    <div
      class="{% if filme.nota >= 8.5 %} btn btn-success{% elif filme.nota >= 6 and filme.nota < 8.5 %} btn btn-warning{% else %}btn btn-danger{% endif %}"
    >
      {{ filme.nota }}
    </div>
  </td>
  <td>
    <button
      class="btn btn-outline-secondary"
      c-get="{{url_for('filmes.detalhe_filmes',filme_id=filme.id)}}"
      c-target="#exibir-filme"
      data-bs-toggle="modal"
      data-bs-target="#exampleModal"
    >
      Ver
    </button>

    <button
      class="btn btn-outline-success"
      c-get="{{url_for('filmes.form_edit_filme',filme_id=filme.id)}}"
      c-target="#form_filme"
    >
      Editar
    </button>

    <button
      class="btn btn-outline-danger"
      c-delete="{{url_for('filmes.deletar_filme',filme_id=filme.id)}}"
      c-remove-closest="tr"
    >
      Deletar
    </button>
  </td>
</tr>
-->

site de filmes/templates/lista_filmes.html
<div class="row">
{% for filme in filmes %}
        {% include 'item_filme.html' %}
      {% endfor %}
</div>